### ISSUE TITLE
provide axLocalize directive

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-angular-adapter#38]
It was determined that axI18n is not big enough in LaxarJS v2 to warrant a standalone module (since the UiKit related i18n stuff is now [part of laxar-uikit](https://github.com/LaxarJS/laxar-uikit/issues/149#issuecomment-285007842), again).

What remains is basically `axLocalize`. If feasible, let's try to find a LaxarJS v1 compatible solution based on the axI18n injection.

**Comment by x1B** [comment]
### BREAKING CHANGE

_Note:_ Strictly speaking, this is not a breaking change within the adapter, but rather a breaking change to LaxarJS UiKit, where the `axLocalize` directive was kept previously. However, since this changelog entry contains the actual, required upgrade information, let's emphasize this one.

The AngularJS directive `axLocalize`, previously provided by LaxarJS UiKit, is now provided by the `laxar-angular-adapter`. The way the directive works was changed as well:

 - **Previously,** the filter took a second parameter `i18n` which was used to read the current localization information from the scope chain.

 - **Now,** the filter still takes a second parameter `i18n`, but expects this to be an `axI18n` widget service instance. Widgets can simply have this service injected, while directives can access it via `axWidgetServices`.


Together with LaxarJS/laxar#429, this has the following implications:

 - The value `$rootScope.i18n` is no longer needed, and this removed with LaxarJS v2.

 - The directive `axBindLocale` is also no longer needed. You can use `axI18n.forFeature( ... )` to obtain different `i18n` instances and to use them with `axLocalize` or with other directives/controls.

**Comment by jpommerening** [comment]
@x1B: Looks great! Care to push a draft so I can give it a try in LaxarJS/ax-html-display-widget#11?
