### ISSUE TITLE
axVisibilityService: overhaul for usage from adapter

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-angular-adapter#7]
Previously the `axVisibilityService` was tightly coupled into the visibility management of areas in LaxarJS. We now break these things apart and moved management of visible / invisible areas into the area helper itself. Hence, we need to find a new way to provide a working visibility handler for controls.

@x1B FYI

**Comment by x1B** [comment]
Implemented on `master` (`v0.3.0`).

### BREAKING CHANGE

The method `axVisibilityService.isVisible()` is no longer available. Instead, use `axVisibilityService.handlerFor( scope ).isVisible()`.

### Upgrade Information

The `axVisibilityService` has been changed to work with the regular `axWidgetServices` injection. To mock its use in tests, you may directly provide a mock yourself or control the mock through the `axVisibility` and `axHeartbeat` mocks that are created by `laxar-mocks`.
